@startuml " bubble-sort"
start
:Enter the Size of the elements ;
:Enter the elements for the given Size;
:Store the elements in the given address;
while (Iterate all array elements from 0th index to N-1 position.And iterate) is (TRUE)
    while (Iterate all array elements from 0th index to num-x-1 position,And iterate them) is (TRUE)
    if (compare current value and next value) is (TRUE) then
        :swap two numbers;
    endif 
    endwhile (False)
endwhile (False)
while (Iterate all array elements from 0th index to num-1 position,And iterate them) is (TRUE)
    :Iterate and print value;
endwhile
stop
@enduml